"""add_is_superadmin

Revision ID: e80ecf186229
Revises: 5217e936474f
Create Date: 2026-07-07 14:10:02.401755
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e80ecf186229'
down_revision: Union[str, None] = '5217e936474f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
